apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rielu-site2-ingress
  namespace: rielu-site2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # 以下の2行を追加
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: rielu.uniproject.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rielu-gen
                port:
                  number: 3000
  tls:
    - hosts:
        - rielu.uniproject.jp
      secretName: rielu-uniproject-jp-tls
